### ISSUE TITLE
The content type is not supported

### ISSUE THREAD

**Issue by Madzi** [oracle/oci-hdfs-connector#22]
The oci-hdfs-connector doesn't provide possibility to setup content type for data set. For example, 

```
outputDataset.coalesce(1)
 .write().mode(SaveMode.Append)
.format("com.databricks.spark.csv")
 .option("header", "true")
 .option("encoding", "UTF-8")
 .csv(outputFolder);
```
keep object without content type and it will be `application/x-octet-stream` (default OCI content).

**Comment by mricken** [comment]
I am not aware of a way in HDFS for the user to specify the content type of a file. We could try guessing it based on the file extension. But unfortunately, you don't set a filename here.

Can you please provide a complete, minimal example that I can download and execute on my machine? I'd like to try what workarounds might be possible.

**Comment by mricken** [comment]
@Madzi, since we have not heard from you in close to four months, I am closing this issue. Please feel free to re-open it, though, to provide additional information.
