### ISSUE TITLE
Missing fs.oci.buffer.dir

### ISSUE THREAD

**Issue by dragon299** [oracle/oci-hdfs-connector#24]
There is a huge among of space needed for the buffer dir during copy process of big files from hdfs to object storage. 

The s3 connector has the option to configure the buffer dir (fs.s3.buffer.dir). This is missing for oci I guess.

**Comment by omkar07** [comment]
Hi @dragon299 , I would like to confirm whether you are asking us to add a property "fs.oci.buffer.dir" which will allow you to use any directory on the local system instead of hadoop.tmp.dir. Also, could you please state why can't you increase the space of hadoop.tmp.dir?

**Comment by dragon299** [comment]
Hi @omkar07, correct. I use the oci-hdfs-connector to copy a huge among of data from hdfs to oci using distcp. Distcp will copy all data to tmp dir bevor start to transfer it to oci. In my case I need a lot of space for this buffer dir and it does not make sense for me to extend /tmp to a few terabytes.

**Comment by omkar07** [comment]
Hi @dragon299 , In that case could you please state why can't you set the hadoop.tmp.dir in the core-site.xml to use any directory on the local system?

**Comment by omkar07** [comment]
Hi @dragon299 , Could you please let us know if you are still facing the above issue? We will close this issue if we don't hear from you by next week.

**Comment by omkar07** [comment]
Hi @dragon299 , Closing this issue since we haven't heard from you.
