### ISSUE TITLE
Add shading logic used to create oci-hdfs-full-<version>.jar

### ISSUE THREAD

**Issue by VaibhavBeriwala** [oracle/oci-hdfs-connector#28]
oci-connector-hdfs's pom currently does not have the logic being used to create the uber jar: **oci-hdfs-full-version-.jar** present in the release assets.
If there are not any concerns, can we please add that shading logic to oci-connector-hdfs's pom as well?

I wanted to shade a couple of more dependencies in that uber-jar.

**Comment by lovababug** [comment]
Hi this part is missing, I am also looking for that. Please provide instruction to build oci-hdfs-full-<version>.jar

**Comment by mricken** [comment]
Hi @VaibhavBeriwala and @lovababug , I have created a development task for our team. We will determine the priority for this task and work on it.

**Comment by omkar07** [comment]
Hi @VaibhavBeriwala and @lovababug, We do have shading logic in the oci-hdfs-full module's pom.xml used to create the uber jar: oci-hdfs-full-version-.jar. Are you suggesting us to add the shading logic in oci-hdfs-connector module's pom.xml too?

**Comment by mricken** [comment]
This has now been released in version 2.9.2.7. Thanks, @omkar07 , for making the change.
