### ISSUE TITLE
Object Storage Connection through Proxy

### ISSUE THREAD

**Issue by rohitagl91** [oracle/oci-hdfs-connector#6]
Hi Team,

Environmnet were I run this Connector has to make all outbound call through HTTP Proxy, but I don't see Proxy support in this connector. can you guys help me on this? this is blocking our major release.

Thanks.

**Comment by sumitkdey** [comment]
Thanks @rohitagl91 for reporting this issue. Support for HTTP proxy in the HDFS connector is dependent upon proxy support being enabled in the Java SDK which the team is currently working on. Once proxy support is enabled in the Java SDK, the work will be started for the HDFS connector. A couple of follow up questions to better understand your use case:
1. Does your setup use multi-part file uploads? If so, can you share your settings i.e part size and number of parallel uploads?
1. Could you confirm that your setup uses a HTTP proxy (and not HTTPS)?

**Comment by rohitagl91** [comment]
Hi @sumitkdey Thanks for quick response! 
1. As of now I am just reading data into spark from Object Storage, there is another Rest service which puts data in Object Storage.
2. My Setup Uses HTTPS proxy, appologies for not mentioning it before.

Can I get any ETA when can I expect it?

**Comment by andy-miles** [comment]
Hi @rohitagl91,

The [2.7.7.0 release](https://github.com/oracle/oci-hdfs-connector/releases/tag/v2.7.7.0) added support for HTTP(S) proxies.  Please refer to the [HDFS Connector for Object Storage](https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/hdfsconnector.htm) documentation for help on configuring your `core-site.xml` accordingly.

**Comment by rohitagl91** [comment]
Thanks! I will test and let you know.
