### ISSUE TITLE
Using Authenticator

### ISSUE THREAD

**Issue by airbots** [oracle/oci-hdfs-connector#8]
I checked the oci-hdfs-connector code. It still using the 4 tuples to do authentication. User just don't need to setup these 4 tuples in the core-site.xml file. However, in your private BasicAuthenticationDetailsProvider createAuthenticator method, it is still looking for the 4 tuples. It means, these 4 tuples should be setup either in Java environment variables or in other config places.

**Comment by sumitkdey** [comment]
Hello @airbots,
Have you tried the steps mentioned at https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/hdfsconnector.htm#two? This describes how you would need to update the core-site.xml to work with the OCI hdfs connector.

**Comment by jodoglevy** [comment]
Hi @airbots , are you still needing assistance? If we don't hear from you in a week, going to close this one.

**Comment by sumitkdey** [comment]
Closing this for now. @airbots Please let us know if the documentation linked above does not resolve your issue.
