### ISSUE TITLE
How to use "Authenticator" as described in Oracle document

### ISSUE THREAD

**Issue by airbots** [oracle/oci-hdfs-connector#9]
I followed the steps, however, I never succeed. Just ask question about how it works. I have create dynamic groups, policies, and compartment following docs. Then, what is the next??? I create a VM in that compartment and the VM will automatically have the privatekey File?

**Comment by airbots** [comment]
I mean the "com.oracle.bmc.hdfs.auth.InstancePrincipalsCustomAuthenticator"

**Comment by sumitkdey** [comment]
Hello @airbots,

You can follow the steps mentioned here https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/hdfsconnector.htm#three to configure using InstancePrincipals for Authentication in the HDFS connector. Do let us know if you ran into issues with this.
